---
title: "R Notebook"
output:
  html_document: default
  html_notebook: default
---

```{r setup, include=F, error=T, message=F, warning=F}
knitr::opts_chunk$set(echo=T, comment=NA, error=T, warning=F, message = F, fig.align = 'center', cache = TRUE, cache.comments = FALSE)
```


```{r}
library(xlsx)

# file location in package
  raw_file <- system.file("extdata", "SK_data.xls", package = "zFactor.DL")

# read the original data from Excel, sheet #1. 
  raw_data <- read.xlsx(raw_file, sheetIndex = 1)
```

```{r}
# number of rows and columns
  dim(raw_data)
  # [1] 2853   60
```

```{r}
# name of the columns
  names(raw_data)
  # colnames(raw_data)
```

```{r}
# change the name of the first three columns to index ".0"
  colnames(raw_data)[1] <- "Ppr.0"
  colnames(raw_data)[2] <- "Tpr.0"
  colnames(raw_data)[3] <- "z.0"

  colnames(raw_data)   # show the column names to verify change

  untidy <- raw_data   # copy data to a new object
```

```{r}
# save untidy dataset to Rda file for package autoload
  # devtools::use_data(untidy) 
  save(untidy, file = "../data/untidy.rda", compress = "xz")
```

